### ISSUE TITLE
[BUG] /francinette-image: permission denied

### ISSUE THREAD

**Issue by kugorang** [WaRtr0/francinette-image#6]
**Describe the bug**

After updating to the latest version, I get the error `permission denied` and `francinette-image` fails to run.

**To Reproduce**

In the terminal, I typed `bash -c “$(curl -fsSL https://raw.githubusercontent.com/WaRtr0/francinette-image/master/update.sh)”`.

**Expected behavior**

The following error message is output, and `paco` is not executed.

```text
Error response from daemon: error while creating mount source path '/francinette-image/temp': mkdir /francinette-image: permission denied
Error: failed to start containers: run-paco
```

**Screenshots**

![image](https://github.com/user-attachments/assets/e7fb578a-5057-4e98-8a75-24d881e1e163)

**Environment**
- OS (Ubuntu, Mac OS): Ubuntu
- Version (20.04): 22.04 LTS
- Console (terminal, Fish, Iterm2...): terminal
...

**Additional context**

It would be nice to have a way to roll back in the `README.md` if this happens.

**Comment by WaRtr0** [comment]
Ow yes! I understand the issue! Adding the /temp mount point turned out to be problematic because Docker creates files with an unknown user, which then causes permission errors when trying to delete the directory.

I'll look into it. Sorry

**Comment by WaRtr0** [comment]
#5

**Comment by kugorang** [comment]
Hi, we would appreciate it if you could check out our newly added [Reply](https://github.com/WaRtr0/francinette-image/discussions/5#discussioncomment-11503787).
